- name: Install Lighthouse
  hosts: lighthouse
  become: true

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Download Lighthouse archive
      get_url:
        url: https://github.com/VKCOM/lighthouse/archive/refs/heads/master.zip
        dest: /tmp/lighthouse.zip

