---
# defaults file for lighthouse-role
lighthouse_version: "master"
lighthouse_url: "https://github.com/VKCOM/lighthouse/archive/refs/heads/{{ lighthouse_version }}.zip"
lighthouse_dest: "/var/www/lighthouse"

