# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
ENV {{ var }}={{ value }}
{% endfor %}
{% endif %}

RUN if command -v apt-get > /dev/null; then \
      apt-get update && apt-get install -y python3 sudo && \
      rm -rf /var/lib/apt/lists/*; \
    elif command -v yum > /dev/null; then \
      yum install -y python3 sudo && yum clean all; \
    fi
