---
- name: Test my_own_role
  hosts: localhost
  connection: local
  roles:
    - role: my_own_namespace.yandex_cloud_elk.file_creator
      vars:
        file_path: /tmp/role_test_file.txt
        file_content: "Content from role"
