{
 "title": "Netology",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Использование памяти",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"nodeexporter\"}",
     "legendFormat": "Вся память"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"}",
     "legendFormat": "Свободная память"
    },
    {
     "expr": "node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes",
     "legendFormat": "Свободно + Кэш + Буффер"
    }
   ]
  },
  {
   "title": "Нагрузка на процессор",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "Утилизация CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Место на файловой системе",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\"}"
    }
   ]
  }
 ]
}