---
driver:
  name: podman

platforms:
  - name: instance
    image: ubuntu:latest
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      host_key_checking: false
      verbosity: 1
      role_name_check: 0

verifier:
  name: ansible

scenario:
  name: compatibility
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy
