folder_id: "b1g7q2a6j9is3l14uqbo"
iam_token: "{{ lookup('env', 'YC_IAM_TOKEN') }}"
zone: ru-central1-e
ubuntu_image_family: ubuntu-2404-lts
clickhouse_version: "26.3.17.4"
clickhouse_packages:
  - clickhouse-common-static
  - clickhouse-client
  - clickhouse-server
clickhouse_internal_ip: "10.128.0.9"
